name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust if using a different branch
  schedule:
    - cron: '0 * * * *'  # Runs the pipeline every hour

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up environment
        run: |
          echo "Setting up environment..."
          sudo apt-get update
          sudo apt-get install -y curl
          echo "soul done join @soulcracks"

  run_script:
    runs-on: ubuntu-latest
    needs: setup_environment
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install telebot pymongo aiohttp
      - name: Make script executable
        run: |
          chmod +x *
      - name: Run script
        run: python3 soul.py

  restart_pipeline:
    runs-on: ubuntu-latest
    needs: run_script
    container:
      image: python:3.9
    steps:
      - name: Sleep for 1 hour
        run: |
          echo "Sleeping for 1 hour before restarting..."
          sleep 3600
      - name: Restart pipeline
        run: |
          echo "Restarting the pipeline..."
          curl -X POST -F token=${{ secrets.GITHUB_TOKEN }} -F ref=${{ github.ref }} https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/dispatches
