name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Environment
        run: echo "Preparing the environment for the pipeline..."

  run_script:
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make Scripts Executable and Run Main Script
        run: |
          chmod +x script1.py script2.py  # Specify actual scripts here
          python3 soul.py

      - name: Store Logs
        if: success()
        run: echo "Logs can be stored here."

  restart_pipeline:
    runs-on: ubuntu-latest
    needs: run_script
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Sleep Before Restarting Pipeline
        run: |
          echo "Sleeping for 1 hour before restarting the pipeline..."
          sleep 3600

      - name: Trigger New Pipeline Execution
        run: |
          echo "Triggering a new pipeline execution..."
          curl -X POST \
            -F token=${{ secrets.CI_JOB_TOKEN }} \
            -F ref=${{ github.ref }} \
            https://gitlab.com/api/v4/projects/${{ secrets.CI_PROJECT_ID }}/trigger/pipeline
